[package]
name = "generate_unicode_data"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
itertools = "0.10"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features= ["full", "fold"] }
unicode_info = { git = "https://github.com/jswalden/unicode-info.git" }
